#!/usr/bin/env python3
"""Generate one static page per project listed in projects/projects.json.

Run from anywhere:  python3 projects/build_projects.py

- "enabled": true  -> projects/<slug>/index.html is generated and listed in projects/index.html
- "enabled": false -> the generated page is removed and the project is not listed

Only pages carrying the GENERATED marker are ever removed, so hand-made folders are safe.
Standard library only.
"""
import html
import json
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECTS_DIR = ROOT / "projects"
MARKER = "<!-- generated by projects/build_projects.py -->"
FONTS = (
    "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400"
    "&family=Inter:wght@300;400;500&display=swap"
)
YEAR = date.today().year

def nav(site, projects):
    return f"""    <nav class="nav" id="nav">
        <a href="{site}" class="nav-logo">FM</a>
        <ul class="nav-links">
            <li><a href="{projects}">Projects</a></li>
            <li><a href="{site}#contact" class="nav-cta">Contact</a></li>
        </ul>
    </nav>"""


def esc(value):
    return html.escape(str(value), quote=True)


def fmt_date(iso):
    d = datetime.strptime(iso, "%Y-%m-%d")
    return f"{d.strftime('%B')} {d.day}, {d.year}"


def head(title, description, site):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {MARKER}
    <title>{esc(title)} — Filipe Moreno</title>
    <meta name="description" content="{esc(description)}">
    <link rel="icon" href="{site}favicon.svg" type="image/svg+xml">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="{FONTS}" rel="stylesheet">
    <link rel="stylesheet" href="{site}styles.css?v=2">
    <link rel="stylesheet" href="{site}projects/projects.css">
</head>
<body>
"""


def footer(back_href, back_label):
    return f"""    <footer>
        <div class="footer-inner">
            <p class="footer-copy">&copy; {YEAR} Filipe Moreno</p>
            <a href="{back_href}" class="footer-back">{back_label}</a>
        </div>
    </footer>
</body>
</html>
"""


def tags_html(tags):
    return "".join(f"<span>{esc(t)}</span>" for t in tags)


def project_page(p):
    actions = [
        f'<a href="{esc(p["repo"])}" target="_blank" rel="noopener" class="btn btn-primary">View on GitHub →</a>'
    ]
    if p.get("homepage"):
        actions.append(
            f'<a href="{esc(p["homepage"])}" target="_blank" rel="noopener" class="btn btn-secondary">Live demo ↗</a>'
        )

    meta = [("Language", p.get("language") or "—"), ("Last update", fmt_date(p["updated"]))]
    meta_html = "".join(f"<div><dt>{esc(k)}</dt><dd>{esc(v)}</dd></div>" for k, v in meta)

    figure = ""
    if p.get("image"):
        figure = (
            f'\n                <figure class="project-figure">'
            f'<img src="{esc(p["image"])}" alt="{esc(p.get("image_alt", p["name"]))}" loading="lazy"></figure>'
        )

    return (
        head(p["name"], p["description"], site="../../")
        + f"""{nav("../../", "../")}
    <main>
        <section class="project-hero">
            <div class="section-inner">
                <span class="section-label">Project</span>
                <h1 class="section-title">{esc(p["name"])}</h1>
                <p class="project-lead">{esc(p["description"])}</p>
                <div class="project-tags">{tags_html(p["tags"])}</div>
                <dl class="project-meta">{meta_html}</dl>
                <div class="project-actions">{"".join(actions)}</div>{figure}
            </div>
        </section>
    </main>
"""
        + footer("../", "← All projects")
    )


FILTER_JS = r"""
    <script>
    (function () {
        const input = document.getElementById('project-search');
        const grid = document.getElementById('projects-grid');
        const cards = Array.from(grid.querySelectorAll('.project-card'));
        const chips = Array.from(document.querySelectorAll('.tag-filter'));
        const count = document.getElementById('project-count');
        const empty = document.getElementById('project-empty');
        const selected = new Set();

        // Every character of `token` appears in `text`, in order (e.g. "lmm" matches "llm").
        function isSubsequence(token, text) {
            let i = 0;
            for (const ch of text) {
                if (ch === token[i]) i++;
                if (i === token.length) return true;
            }
            return false;
        }

        // 2 = substring match, 1 = fuzzy match, 0 = no match.
        function scoreToken(token, text) {
            if (text.includes(token)) return 2;
            return isSubsequence(token, text) ? 1 : 0;
        }

        function update() {
            const tokens = input.value.trim().toLowerCase().split(/\s+/).filter(Boolean);
            const matches = [];

            cards.forEach(card => {
                const tags = card.dataset.tags.toLowerCase().split('|');
                const hasTags = [...selected].every(tag => tags.includes(tag));
                let total = 0;
                for (const token of tokens) {
                    const s = scoreToken(token, card.dataset.search);
                    if (s === 0) { total = -1; break; }
                    total += s;
                }
                const visible = hasTags && total >= 0;
                card.hidden = !visible;
                if (visible) matches.push({ card, total });
            });

            // Best matches first; ties keep the default order (most recently updated).
            matches.sort((a, b) => b.total - a.total);
            matches.forEach(m => grid.appendChild(m.card));

            count.textContent = matches.length + ' of ' + cards.length + ' projects';
            empty.hidden = matches.length > 0;
        }

        chips.forEach(chip => {
            chip.addEventListener('click', () => {
                const tag = chip.dataset.tag.toLowerCase();
                if (selected.has(tag)) selected.delete(tag); else selected.add(tag);
                chip.setAttribute('aria-pressed', selected.has(tag) ? 'true' : 'false');
                update();
            });
        });
        input.addEventListener('input', update);
        update();
    })();
    </script>
"""


def index_page(projects):
    cards = "".join(
        f"""
                <a href="./{esc(p["slug"])}/" class="project-card" data-search="{esc(search_text(p))}" data-tags="{esc("|".join(t.lower() for t in filter_tags(p)))}">
                    <div class="project-header">
                        <h3 class="project-name">{esc(p["name"])}</h3>
                        <span class="project-arrow">→</span>
                    </div>
                    <p class="project-desc">{esc(p["description"])}</p>
                    <div class="project-tags">{tags_html(p["tags"])}</div>
                </a>"""
        for p in projects
    )

    # One chip per tag or language shared by at least two projects; rarer ones are found by search.
    counts = {}
    for p in projects:
        for t in filter_tags(p):
            counts[t] = counts.get(t, 0) + 1
    chips = "".join(
        f'<button type="button" class="tag-filter" data-tag="{esc(t)}" aria-pressed="false">'
        f'{esc(t)} <small>{n}</small></button>'
        for t, n in sorted(counts.items(), key=lambda kv: kv[0].lower())
        if n >= 2
    )

    return (
        head("All projects", "Public repositories by Filipe Moreno, one page each.", site="../")
        + f"""{nav("../", "./")}
    <main>
        <section class="projects-index">
            <div class="section-inner">
                <span class="section-label">Projects</span>
                <h1 class="section-title">Things I've built</h1>
                <p class="project-lead">Public repositories, one page each. Most recently updated first.</p>

                <div class="projects-toolbar">
                    <input id="project-search" class="project-search" type="search" autocomplete="off"
                        placeholder="Search by name, tag or language…" aria-label="Search projects">
                    <div class="project-filters" role="group" aria-label="Filter by tag">{chips}</div>
                    <p class="project-count" id="project-count" aria-live="polite"></p>
                </div>

                <div class="projects-grid" id="projects-grid">{cards}
                </div>
                <p class="project-empty" id="project-empty" hidden>No projects match these filters.</p>
            </div>
        </section>
    </main>
"""
        + footer("../", "Back to portfolio ↑")
        + FILTER_JS
    )


def filter_tags(p):
    """Tags plus language, de-duplicated case-insensitively, original casing kept."""
    seen, out = set(), []
    for t in list(p["tags"]) + ([p["language"]] if p.get("language") else []):
        if t.lower() not in seen:
            seen.add(t.lower())
            out.append(t)
    return out


def search_text(p):
    return " ".join([p["name"], p["description"], *filter_tags(p)]).lower()


def main():
    data = json.loads((PROJECTS_DIR / "projects.json").read_text(encoding="utf-8"))
    listed = []

    for p in data["projects"]:
        slug = p["slug"]
        if not slug or "/" in slug:
            raise SystemExit(f"invalid slug: {slug!r}")

        folder = PROJECTS_DIR / slug
        page = folder / "index.html"

        if p.get("enabled", True):
            folder.mkdir(exist_ok=True)
            page.write_text(project_page(p), encoding="utf-8")
            listed.append(p)
        elif page.exists() and MARKER in page.read_text(encoding="utf-8"):
            page.unlink()
            try:
                folder.rmdir()
            except OSError:
                pass
            print(f"removed disabled project page: {slug}")

    listed.sort(key=lambda p: p["updated"], reverse=True)
    (PROJECTS_DIR / "index.html").write_text(index_page(listed), encoding="utf-8")
    print(f"generated {len(listed)} project pages + projects/index.html")


if __name__ == "__main__":
    main()
