#!/usr/bin/env python3
"""Generate one static page per project listed in projects/projects.json.

Run from anywhere:  python3 projects/build_projects.py

- "enabled": true  -> <slug>/index.html is generated and listed in projects/index.html
- "enabled": false -> the generated page is removed and the project is not listed

Only pages carrying the GENERATED marker are ever removed, so hand-made folders are safe.
Standard library only.
"""
import html
import json
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECTS_DIR = ROOT / "projects"
MARKER = "<!-- generated by projects/build_projects.py -->"
FONTS = (
    "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400"
    "&family=Inter:wght@300;400;500&display=swap"
)
YEAR = date.today().year

NAV = """    <nav class="nav" id="nav">
        <a href="../" class="nav-logo">FM</a>
        <ul class="nav-links">
            <li><a href="../projects/">Projects</a></li>
            <li><a href="../#contact" class="nav-cta">Contact</a></li>
        </ul>
    </nav>"""


def esc(value):
    return html.escape(str(value), quote=True)


def fmt_date(iso):
    d = datetime.strptime(iso, "%Y-%m-%d")
    return f"{d.strftime('%B')} {d.day}, {d.year}"


def head(title, description):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {MARKER}
    <title>{esc(title)} — Filipe Moreno</title>
    <meta name="description" content="{esc(description)}">
    <link rel="icon" href="../favicon.svg" type="image/svg+xml">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="{FONTS}" rel="stylesheet">
    <link rel="stylesheet" href="../styles.css?v=2">
    <link rel="stylesheet" href="../projects/projects.css">
</head>
<body>
"""


def footer(back_href, back_label):
    return f"""    <footer>
        <div class="footer-inner">
            <p class="footer-copy">&copy; {YEAR} Filipe Moreno</p>
            <a href="{back_href}" class="footer-back">{back_label}</a>
        </div>
    </footer>
</body>
</html>
"""


def tags_html(tags):
    return "".join(f"<span>{esc(t)}</span>" for t in tags)


def project_page(p):
    actions = [
        f'<a href="{esc(p["repo"])}" target="_blank" rel="noopener" class="btn btn-primary">View on GitHub →</a>'
    ]
    if p.get("homepage"):
        actions.append(
            f'<a href="{esc(p["homepage"])}" target="_blank" rel="noopener" class="btn btn-secondary">Live demo ↗</a>'
        )

    meta = [("Language", p.get("language") or "—"), ("Last update", fmt_date(p["updated"]))]
    meta_html = "".join(f"<div><dt>{esc(k)}</dt><dd>{esc(v)}</dd></div>" for k, v in meta)

    figure = ""
    if p.get("image"):
        figure = (
            f'\n                <figure class="project-figure">'
            f'<img src="{esc(p["image"])}" alt="{esc(p.get("image_alt", p["name"]))}" loading="lazy"></figure>'
        )

    return (
        head(p["name"], p["description"])
        + f"""{NAV}
    <main>
        <section class="project-hero">
            <div class="section-inner">
                <span class="section-label">Project</span>
                <h1 class="section-title">{esc(p["name"])}</h1>
                <p class="project-lead">{esc(p["description"])}</p>
                <div class="project-tags">{tags_html(p["tags"])}</div>
                <dl class="project-meta">{meta_html}</dl>
                <div class="project-actions">{"".join(actions)}</div>{figure}
            </div>
        </section>
    </main>
"""
        + footer("../projects/", "← All projects")
    )


def index_page(projects):
    cards = "".join(
        f"""
                <a href="../{esc(p["slug"])}/" class="project-card">
                    <div class="project-header">
                        <h3 class="project-name">{esc(p["name"])}</h3>
                        <span class="project-arrow">→</span>
                    </div>
                    <p class="project-desc">{esc(p["description"])}</p>
                    <div class="project-tags">{tags_html(p["tags"])}</div>
                </a>"""
        for p in projects
    )
    return (
        head("All projects", "Public repositories by Filipe Moreno, one page each.")
        + f"""{NAV}
    <main>
        <section class="projects-index">
            <div class="section-inner">
                <span class="section-label">Projects</span>
                <h1 class="section-title">Things I've built</h1>
                <p class="project-lead">Public repositories, one page each. Most recently updated first.</p>
                <div class="projects-grid">{cards}
                </div>
            </div>
        </section>
    </main>
"""
        + footer("../", "Back to portfolio ↑")
    )


def main():
    data = json.loads((PROJECTS_DIR / "projects.json").read_text(encoding="utf-8"))
    listed = []

    for p in data["projects"]:
        slug = p["slug"]
        if not slug or "/" in slug or slug == "projects":
            raise SystemExit(f"invalid slug: {slug!r}")

        folder = ROOT / slug
        page = folder / "index.html"

        if p.get("enabled", True):
            folder.mkdir(exist_ok=True)
            page.write_text(project_page(p), encoding="utf-8")
            listed.append(p)
        elif page.exists() and MARKER in page.read_text(encoding="utf-8"):
            page.unlink()
            try:
                folder.rmdir()
            except OSError:
                pass
            print(f"removed disabled project page: {slug}")

    listed.sort(key=lambda p: p["updated"], reverse=True)
    (PROJECTS_DIR / "index.html").write_text(index_page(listed), encoding="utf-8")
    print(f"generated {len(listed)} project pages + projects/index.html")


if __name__ == "__main__":
    main()
